### ISSUE TITLE
Exception during impex header fields reorganization

### ISSUE THREAD

**Issue by SamuelGeiger** [Janhouse/sap-commerce-integration-intellij-idea-plugin#4]
**During the work with the following impex content**
> INSERT_UPDATE Customer;customerID;customerNumber;accountBalance;backOfficeLoginDisabled;blacklistedBySyncJob;country(iso3code,isocode)[unique=true,allownull=true];dateOfBirth[dateformat=dd.MM.yyyy hh:mm:ss];deactivationDate[dateformat=dd.MM.yyyy hh:mm:ss];defaultEmailContactInfo(pk);defaultPaymentAddress(code);defaultPaymentInfo(pk);defaultPhoneContactInfo(pk);defaultShipmentAddress(code);deleted;deletionComment;deletionDate[dateformat=dd.MM.yyyy hh:mm:ss];description;domain;email[unique=true,allownull=true];encodedPassword;passwordEncoding;fallbackDeliveryCost;fallbackDiscount;firstName;hkmc;hmcLoginDisabled;iSchichtCustomerId;isGuestCustomer;lastName;mayNotOrder;mayOnlyUseSafePaymentMethods;migrated;migratedUID[unique=true];name;orderCustomerId;originalUid;preferredPaymentModeErpCode(code,itemtype(code));previewCatalogVersions(catalog(id),version);refreshed;retentionState(code,itemtype(code));sessionCurrency(isocode);sessionLanguage(isocode);title(code);token;uid[unique=true,allownull=true];userprofile(pk);visCustomerNoHint

**I got this stacktrace**

```
Wrong range in reference com.intellij.idea.plugin.hybris.impex.psi.references.TypeSystemAttributeReference(ImpexAnyHeaderParameterNameImpl(ANY_HEADER_PARAMETER_NAME):(0,14)): (0,14). Reference text: 'customerID'

java.lang.StringIndexOutOfBoundsException: Can't extract (0,14) range from 'customerID'
	at com.intellij.openapi.util.TextRange.substring(TextRange.java:121)
	at com.intellij.psi.PsiReferenceBase.getValue(PsiReferenceBase.java:84)
	at com.intellij.psi.PsiReferenceBase.getCanonicalText(PsiReferenceBase.java:114)
	at com.intellij.idea.plugin.hybris.impex.inspection.ImpexHeaderLineVisitor.visitAnyHeaderParameterName(UnknownTypeAttributeInspection.kt:51)
	at com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexAnyHeaderParameterNameImpl.accept(ImpexAnyHeaderParameterNameImpl.java:21)
	at com.intellij.idea.plugin.hybris.impex.psi.impl.ImpexAnyHeaderParameterNameImpl.accept(ImpexAnyHeaderParameterNameImpl.java:25)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:268)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:200)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
**Update 27.11.2019:**
Happend again:
```Wrong range in reference com.intellij.idea.plugin.hybris.impex.psi.references.TypeSystemAttributeReference(ImpexAnyHeaderParameterNameImpl(ANY_HEADER_PARAMETER_NAME):(0,12)): (0,12). Reference text: 'essageFired'

java.lang.StringIndexOutOfBoundsException: Can't extract (0,12) range from 'essageFired'
	at com.intellij.openapi.util.TextRange.substring(TextRange.java:121)
```

**Comment by marcusaureliusalves** [comment]
I've got this

`
java.lang.StringIndexOutOfBoundsException: Can't extract (0,17) range from 'description' at com.intellij.openapi.util.TextRange.substring(TextRange.java:121)
`
